#Trabajo Práctico 2 - Numpy

In [6]:
import numpy as np
from google.colab import drive
drive.mount('/content/drive')
import random

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


##Ejercicio 1

In [ ]:
a = float(input("Ingrese un valor a: "))
b = float(input("Ingrese un valor b: "))
c = float(input("Ingrese un valor c: "))
d = float(input("Ingrese un valor d: "))

Ingrese un valor a: 2
Ingrese un valor b: 6
Ingrese un valor c: 10
Ingrese un valor d: 432


In [ ]:
u = np.array((a,b))
v = np.array((c,d))

print(u)
print(v)

[2. 6.]
[ 10. 432.]


In [ ]:
print(v -u)
print(-v - u)
print(u*2 - v)
print(0.5*u - 2*v)

[  8. 426.]
[ -12. -438.]
[  -6. -420.]
[ -19. -861.]


## Ejercicio 2

In [ ]:
#Guardamos la ruta del archivo en una variable para su fácil manejo

rutaArchivo = "/content/drive/MyDrive/Colab Notebooks/2° Cuatri Python/Archivos varios/stock.txt"

In [ ]:
#Abrimos el archivo

archivo = open(rutaArchivo, "r")

In [ ]:
#Leemos el archivo e imprimimos su contenido

contenidoArchivo = archivo.read()
print(contenidoArchivo)

heladera
79999.99
4
microondas
24539.66
8
licuadora
5608.25
13
pava electrica
4950.75
22
exprimidor electrico
2243.33
17
secarropas
321421.33
15
heelado
42.3
42


In [ ]:
#Separamos todas las líneas del archivo y guardamos el contenido de cada una como items de una lista

lineasDelArchivo = contenidoArchivo.splitlines()
print(lineasDelArchivo)

['heladera', '79999.99', '4', 'microondas', '24539.66', '8', 'licuadora', '5608.25', '13', 'pava electrica', '4950.75', '22', 'exprimidor electrico', '2243.33', '17', 'secarropas', '321421.33', '15', 'heelado', '42.3', '42']


In [ ]:
#Convertimos esa lista en un Numpy Array

arrLineasArchivo = np.array(lineasDelArchivo)
print(arrLineasArchivo)

['heladera' '79999.99' '4' 'microondas' '24539.66' '8' 'licuadora'
 '5608.25' '13' 'pava electrica' '4950.75' '22' 'exprimidor electrico'
 '2243.33' '17' 'secarropas' '321421.33' '15' 'heelado' '42.3' '42']


In [ ]:
#Reformamos la forma del array, aprovechando su simetría, generando 3 columnas

matrizReformada = np.reshape(arrLineasArchivo, (-1,3))
print(matrizReformada)

[['heladera' '79999.99' '4']
 ['microondas' '24539.66' '8']
 ['licuadora' '5608.25' '13']
 ['pava electrica' '4950.75' '22']
 ['exprimidor electrico' '2243.33' '17']
 ['secarropas' '321421.33' '15']
 ['heelado' '42.3' '42']]


In [ ]:
#Separamos ese array (Que ya es una matriz) en 3 vectores que contengan un item específico cada uno

vectorArticulos = matrizReformada[:, 0]
vectorPrecios = matrizReformada[:, 1].astype(float)
vectorStock = matrizReformada[:, 2].astype(int)

print(vectorArticulos)
print(vectorPrecios)
print(vectorStock)

['heladera' 'microondas' 'licuadora' 'pava electrica'
 'exprimidor electrico' 'secarropas' 'heelado']
[7.9999990e+04 2.4539660e+04 5.6082500e+03 4.9507500e+03 2.2433300e+03
 3.2142133e+05 4.2300000e+01]
[ 4  8 13 22 17 15 42]


In [ ]:
# Forma alternativa

#[vector_1, vector_2, vector_3] = np.split(ary = matrizReformada,
                                          #indices_or_sections = 3,
                                          #axis = 1)

## Ejercicio 3

In [ ]:
def consultar():
  articulo = input("Ingrese el nombre de un producto: ")
  articulo = articulo.lower()
  if articulo in vectorArticulos:
    posicion = np.where(vectorArticulos == articulo)
    print(f"Artículo: {vectorArticulos[posicion]}")
    print(f"Precio: {vectorPrecios[posicion]}")
    print(f"Stock: {vectorStock[posicion]}")
  else:
    print("No se encuentra el artículo ingresado")


## Ejercicio 4

In [ ]:
def comprar(producto):
  posicion = np.where(vectorArticulos == producto)
  if vectorStock[posicion] >= 1:
    vectorStock[posicion] -= 1
    return True
  else:
    return False

In [ ]:
consultar()
comprar("microondas")
consultar()

Ingrese el nombre de un producto: microondas
Artículo: ['microondas']
Precio: [24539.66]
Stock: [8]
Ingrese el nombre de un producto: microondas
Artículo: ['microondas']
Precio: [24539.66]
Stock: [7]


## Ejercicio 5

In [ ]:
def agregar(producto, precio, cantidad):
  global vectorArticulos, vectorPrecios, vectorStock
  producto = producto.lower()
  if producto not in vectorArticulos:
    vectorArticulos = np.append(vectorArticulos, producto)
    vectorPrecios = np.append(vectorPrecios, precio)
    vectorStock = np.append(vectorStock, cantidad)
    return True
  else:
    print("El artículo ya existe.")
    return False

In [ ]:
def reponer(producto, cantidad):
  if producto in vectorArticulos:
    posicion = np.where(vectorArticulos == producto)
    vectorStock[posicion] += cantidad
    return True
  else:
    print("El artículo no existe.")
    return False

In [ ]:
agregar("horno", 75000, 10)
consultar()
reponer("horno", 5)
consultar()
comprar("horno")
consultar()

Ingrese el nombre de un producto: horno
Artículo: ['horno']
Precio: [75000.]
Stock: [10]
Ingrese el nombre de un producto: horno
Artículo: ['horno']
Precio: [75000.]
Stock: [15]
Ingrese el nombre de un producto: horno
Artículo: ['horno']
Precio: [75000.]
Stock: [14]


## Ejercicio 6

In [ ]:
def generar_billetes(CantidadBilletes):
  billeteAleatorio = np.random.randint(low= 0, high= 5, size=(CantidadBilletes,4))
  return billeteAleatorio

In [ ]:
billeteGanador = generar_billetes(1)
print(billeteGanador)

[[2 2 2 2]]


In [ ]:
matrizParticipantes = generar_billetes(10)
matrizParticipantes

array([[4, 3, 2, 0],
       [4, 1, 1, 4],
       [4, 3, 3, 3],
       [2, 3, 4, 2],
       [2, 2, 2, 3],
       [3, 4, 0, 3],
       [2, 1, 4, 3],
       [4, 3, 2, 0],
       [4, 3, 2, 3],
       [1, 3, 0, 4]])

In [ ]:
matrizParticipantes = generar_billetes(10)
matrizParticipantes[6] = billeteGanador
matrizParticipantes

array([[0, 4, 1, 2],
       [4, 3, 1, 4],
       [2, 3, 3, 1],
       [3, 1, 4, 0],
       [1, 4, 4, 4],
       [1, 0, 3, 1],
       [2, 2, 2, 2],
       [1, 4, 0, 0],
       [3, 1, 4, 3],
       [2, 0, 4, 3]])

In [ ]:
def verificar_coincidencias(billeteGanador, matrizParticipantes):
  coincidencias = np.sum(billeteGanador == matrizParticipantes, axis=1)
  return coincidencias

In [ ]:
coincidencias = billeteGanador == matrizParticipantes
coincidencias

array([[False, False, False, False],
       [False,  True,  True, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [ True, False, False,  True],
       [False, False,  True, False],
       [False, False, False,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [ ]:
print(f"Billete ganador: {billeteGanador}")
print(f"Billetes participantes:\n {matrizParticipantes}")
print(f"Coincidencias: {verificar_coincidencias(billeteGanador, matrizParticipantes)}")

Billete ganador: [[2 2 2 2]]
Billetes participantes:
 [[0 4 1 2]
 [4 3 1 4]
 [2 2 2 2]
 [3 1 4 0]
 [1 4 4 4]
 [1 0 3 1]
 [2 2 2 2]
 [1 4 0 0]
 [3 1 4 3]
 [2 0 4 3]]
Coincidencias: [1 0 4 0 0 0 4 0 0 1]


In [ ]:
#Opcional 1

def todoEnUno(numerosPorBillete, inicioRangoNumeros, finRangoNumeros, cantidadParticipantes):
  billeteGanador = np.random.randint(low= inicioRangoNumeros, high= finRangoNumeros, size=(1,numerosPorBillete))
  matrizParticipantes = np.random.randint(low= inicioRangoNumeros, high= finRangoNumeros, size=(cantidadParticipantes,numerosPorBillete))
  coincidencias = np.sum(billeteGanador == matrizParticipantes, axis=1)
  return billeteGanador, matrizParticipantes, coincidencias

pruebaLoteria = todoEnUno(10,0, 31, 5)
print(f"Billete ganador:\n {pruebaLoteria[0]}")
print(f"Billetes participantes:\n {pruebaLoteria[1]}")
print(f"Coincidencias:\n {pruebaLoteria[2]}")

Billete ganador:
 [[ 1 16  5 13  5 19 10 29  8 25]]
Billetes participantes:
 [[ 0 29 28 29  0 20  2  9  0 11]
 [ 0 16  4  3 28 16  4 29 24  6]
 [11 14 27 28 12 21 30  5  5 10]
 [ 4 12  8  2  5 15 18 13 13  9]
 [23 16 27 12  6 24 24 26  1  7]]
Coincidencias:
 [0 2 0 1 1]


## Ejercicio 7

In [44]:
# Señal a decodificar
senal = '010010000110111101101100011000010100110101110101011011100110010001101111'


In [41]:
# Convertir la señal en un array de enteros de 0 y 1
bits_array = np.array(list(senal), dtype=int)

# Reformar el array en un conjunto de filas de 8 columnas (paquetes de 8 bits)
bits_reshaped = bits_array.reshape(-1, 8)
bits_reshaped

array([[0, 1, 0, 0, 1, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 1, 1],
       [0, 1, 1, 0, 1, 1, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 1, 0, 1],
       [0, 1, 1, 1, 0, 1, 0, 1],
       [0, 1, 1, 0, 1, 1, 1, 0],
       [0, 1, 1, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 1, 1, 1, 1]])

In [42]:
# Crear un vector de potencias de 2 para convertir de binario a decimal
potencias_dos = 2 ** np.arange(7, -1, -1)


# Multiplicar cada paquete de 8 bits por las potencias de 2 y sumar para obtener el valor decimal
valores_decimales = bits_reshaped.dot(potencias_dos)
valores_decimales

array([ 72, 111, 108,  97,  77, 117, 110, 100, 111])

In [43]:
# Convertir los valores decimales a caracteres ASCII
mensaje = ''.join(np.char.mod('%c', valores_decimales))

# Mostrar el mensaje decodificado
print("Mensaje descifrado:", mensaje)

Mensaje descifrado: HolaMundo
